apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "redfish-insights.fullname" . }}-backend
  labels:
    {{- include "redfish-insights.labels" . | nindent 4 }}
rules:
  - apiGroups: ["metal3.io"]
    resources: ["baremetalhosts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: []
