apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redfish-insights.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "redfish-insights.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
