# helm/openshift-redfish-insights/templates/plugin-consoleplugin.yaml
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: redfish-insights-plugin
  labels:
    {{- include "redfish-insights.labels" . | nindent 4 }}
spec:
  displayName: "Firmware Insights"
  backend:
    type: Service
    service:
      name: {{ include "redfish-insights.fullname" . }}-plugin
      namespace: {{ .Values.namespace.name }}
      port: {{ .Values.plugin.service.port }}
      basePath: "/"
  proxy:
    - alias: redfish-insights
      endpoint:
        type: Service
        service:
          name: {{ include "redfish-insights.fullname" . }}-backend
          namespace: {{ .Values.namespace.name }}
          port: {{ .Values.backend.service.port }}
      authorize: true
