# helm/openshift-baremetal-insights/templates/backend-ca-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baremetal-insights.fullname" . }}-backend-ca
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "baremetal-insights.labels" . | nindent 4 }}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}
