# helm/openshift-baremetal-insights/templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "baremetal-insights.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "baremetal-insights.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "baremetal-insights.fullname" . }}-backend-cert
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "baremetal-insights.backend.selectorLabels" . | nindent 4 }}
