apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "redfish-insights.fullname" . }}-backend
  labels:
    {{- include "redfish-insights.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "redfish-insights.fullname" . }}-backend
subjects:
  - kind: ServiceAccount
    name: {{ include "redfish-insights.fullname" . }}-backend
    namespace: {{ .Values.namespace.name }}
