# helm/openshift-redfish-insights/templates/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redfish-insights.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "redfish-insights.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "redfish-insights.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redfish-insights.backend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "redfish-insights.fullname" . }}-backend
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: TLS_CERT_FILE
              value: /var/serving-cert/tls.crt
            - name: TLS_KEY_FILE
              value: /var/serving-cert/tls.key
          envFrom:
            - configMapRef:
                name: {{ include "redfish-insights.fullname" . }}-backend
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            - name: backend-serving-cert
              mountPath: /var/serving-cert
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: backend-serving-cert
          secret:
            secretName: {{ include "redfish-insights.fullname" . }}-backend-cert
