# helm/openshift-baremetal-insights/templates/backend-servicemonitor.yaml
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "baremetal-insights.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "baremetal-insights.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      {{- include "baremetal-insights.backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: 30s
{{- end }}
