# helm/openshift-baremetal-insights/templates/plugin-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "baremetal-insights.fullname" . }}-plugin
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "baremetal-insights.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "baremetal-insights.fullname" . }}-plugin-cert
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.plugin.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "baremetal-insights.plugin.selectorLabels" . | nindent 4 }}
