apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: baremetal-insights-plugin
spec:
  displayName: "Firmware Insights"
  backend:
    type: Service
    service:
      name: baremetal-insights-plugin
      namespace: baremetal-insights
      port: 9443
      basePath: "/"
  proxy:
    - alias: baremetal-insights
      authorize: true
      endpoint:
        type: Service
        service:
          name: openshift-baremetal-insights
          namespace: baremetal-insights
          port: 8080
