apiVersion: apps/v1
kind: Deployment
metadata:
  name: baremetal-insights-plugin
  namespace: baremetal-insights
  labels:
    app: baremetal-insights-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baremetal-insights-plugin
  template:
    metadata:
      labels:
        app: baremetal-insights-plugin
    spec:
      containers:
        - name: plugin
          image: baremetal-insights-plugin:latest
          ports:
            - containerPort: 9443
              protocol: TCP
          volumeMounts:
            - name: serving-cert
              mountPath: /var/cert
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: serving-cert
          secret:
            secretName: baremetal-insights-plugin-cert
