apiVersion: v1
kind: Service
metadata:
  name: redfish-insights-plugin
  namespace: redfish-insights
  labels:
    app: redfish-insights-plugin
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: redfish-insights-plugin-cert
spec:
  type: ClusterIP
  ports:
    - port: 9443
      targetPort: 9443
      protocol: TCP
  selector:
    app: redfish-insights-plugin
