# helm/openshift-redfish-insights/Chart.yaml
apiVersion: v2
name: openshift-redfish-insights
description: Firmware visibility for Dell servers in OpenShift
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - openshift
  - firmware
  - dell
  - redfish
maintainers:
  - name: Craig Robinson
